apiVersion: v1
kind: Pod
metadata:
   name: my-labels
   labels:
    - trainer: raghu
      course: devops
spec:
  containers:
    - name: labels 
      image: nginx
      ports:
       - containerPort: 80