apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  namespace: mynamespace
spec:
  containers:
    - name: resource
      image: nginx
      resources:
        requests:
          memory: "124Mi"
          cpu: "130m"
        limits:
          memory: "140Mi"
          cpu: "150m"
      ports:
        - containerPort: 80
