apiVersion: v1
kind: Pod
metadata:
 name: pod-loadbalancer
 labels: 
  app: devops
  duration: 3hours
spec:
  containers:
   - name: pod-loadbalancer
     image: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: pod-service
spec:
 type: loadbalance
 selector:
   app: devops
   duration: 3hours
 ports:
  - protocol: TCP
    port: 80
    targetPort: 9376

