apiVersion: v1
kind: Pod
metadata: 
  name: pod-nodeport
  labels:
   app: roboshop
   tier: web
spec:
  containers:
   - name: pod-nodeport
     image: nginx
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: service-nodeport
spec:
  type: nodeport
  app: roboshop
  tier: web
  ports:
    - protocol: TCP
      port: 80
      targetport: 9376
   

